- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  pre_tasks:
    - name: Update dnf
      become: true
      ansible.builtin.dnf:
        update_cache: true
        state: present
      tags:
        - base
  tasks:
    - include_tasks: tasks/base.yml
    - include_tasks: tasks/git.yml
    - include_tasks: tasks/docker.yml
