- name: Setup the docker rpm repository
  become: true
  ansible.builtin.dnf:
    name: dnf-plugins-core
  tags:
    - docker
- name: Add the repository itself
  become: true
  ansible.builtin.shell: "dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo"
  tags:
    - docker
- name: Install docker engine from dnf
  become: true
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
- name: Start the docker service
  become: true
  ansible.builtin.systemd_service:
    name: docker
    state: started
    enabled: true

